# Site settings
title: Marcelo Andrade .info
email: email@marceloandrade.info
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marceloandrade.info"
permalink: /:title
twitter_username: mfandrade
github_username:  mfandrade

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: _posts
    values:
      lang: pt
  -
    scope:
      path: _posts/en
    values:
      lang: en
  -
    scope:
      path: _posts/es
    values:
      lang: es
